/*
Even Fibonacci numbers

Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

#include <stdio.h>

unsigned long even_fibonacci_sum(unsigned long limit) {

    unsigned long current = 1; 
    unsigned long last    = 0; 
    unsigned long sum     = 0;
    unsigned long buffer;

    while (current < limit) {

        if (current % 2 == 0) {
            sum += current;
        }

        buffer  = current;
        current = current + last;
        last    = buffer;
        
    }

    return sum;
}

int main(int argc, char* argv[]) {

    printf("\n\n%ld\n\n", even_fibonacci_sum(4000000));

    return 0;
} 